Tickets/dm 33673
lsst-ts/ts_labview_tcp_json pull request #34
Opened 2022-02-15 20:53 UTC by pcortes80

Modified attributes related to queue´s size/timeout, and updated dependences/documentation.

2022-02-16 19:24 UTC, teweitsai requested changes
Please rename the attributes and accessor methods.

2022-02-16 19:24 UTC, teweitsai commented on simulator/README.md
> +- queueTcpClientFromDdsMaxSize = 1000
maxSizeQueueTcpClientFromDds

2022-02-16 19:24 UTC, teweitsai commented on simulator/README.md
> +- queueTcpClientFromDdsTimeout (ms) = 50
timeoutQueueTcpClientFromDds

2022-02-16 19:24 UTC, teweitsai commented on simulator/README.md
> +- queueTcpClientMaxSize = 100
maxSizeQueueTcpClient

2022-02-18 16:29 UTC, pcortes80 commented on doc/versionHistory.md
> +- Modify **isQueueTcpClientFull.vi**, **getTelElement.vi** and **flushTelQueue.vi** in `TcpServer` class, so the user needs to update this vis in their callers."
Done.

2022-02-18 16:30 UTC, pcortes80 commented on simulator/README.md
> +- queueTcpClientFromDdsTimeout (ms) = 50
Done.

2022-02-18 16:30 UTC, pcortes80 commented on simulator/README.md
> +- queueTcpClientMaxSize = 100
Done.

2022-02-18 16:31 UTC, closed without merging